name: magic_8_ball
description: A sample command-line application.
# version: 1.0.0
# homepage: https://www.example.com
# author: Your Name <email@example.com>

environment:
  sdk: '>=2.2.0 <3.0.0'

#dependencies:
#  path: ^1.4.1
dart_random_choice: ^0.0.2


dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
